### ISSUE TITLE
Infinite scroller scrolls very slowly by wheel or keyboard on Firefox

### ISSUE THREAD

**Issue by flackr** [GoogleChrome/ui-element-samples#43]
Wheel scrolling or keyboard scrolling the infinite scrolling sample moves very slowly on Firefox. I think it's a bad interaction with smooth scroll and setting the scroll position in case sizes have changed. It's not a performance problem, the scroll is quite fast if you drag the scrollbar.

**Comment by GordoRank** [comment]
Chrome, Edge, and other browsers apply a mousewheel override when scrolling elements.  This override effectively doubles the distance traveled per wheel/keyboard 'tick', versus the system OS settings.

Firefox, on the other hand, only applies this override on the root element.  

Since the infinite scroller uses a scrollable element, the result is slow mousewheel/keyboard scrolling compared with other browsers.

I've filed a bug with Mozilla regarding this, but they don't seem too willing to rectify the issue.  They are of the opinion that applying the mousewheel override on all elements would mean that small scrollable elements would then be scrolling too fast.  The result is a frustrating disparity in mousewheel scrolling in Firefox alone.

While their approach may have made sense in the past, modern web apps are increasingly using scrollable elements.  Therefore, I feel that their decision is 'out-of-date' and not inline with the needs of the modern web.

Here is my original bug regarding this issue:

https://bugzilla.mozilla.org/show_bug.cgi?id=1217715

**Comment by fahrradflucht** [comment]
While I totally agree with you about the issue, I think encouraging people to file duplicate bugs won't get us anywhere. This is just ignorant for the people doing issue triage on Bugzilla.

**Comment by GordoRank** [comment]
Indeed, you're quite right of course.  I've edited my comment to reflect this.

**Comment by fahrradflucht** [comment]
It's fixed in Firefox 50 I think, so this can probably be closed.

**Comment by laszbalo** [comment]
Still experiencing the described behavior on Firefox 50 for Ubuntu canonical - 1.0.
